#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /authentication_token
    methods: ['POST']


get_user:
    path: /authenticated
    controller: App\Controller\AuthenController::getAgirUser
    methods: ['GET']